#!/bin/bash

WHEN=$1
I=0
while [[ $I -lt $WHEN ]]; do
  NAME=$(date -d "-$I days" +"%Y-%m-%d")
  FILE="$NAME.md"
  if [[ -e $FILE ]]; then
    DONE=$(cat $FILE | grep "\[[Xx-]\]" | sort | wc -l)
    if [[ $DONE -gt 0 ]]; then
      echo "Done on $NAME"
      cat $FILE | grep "\[[Xx-]\]" | sort
      echo ""
    fi
  fi
  I=$((I+1))
done

