#!/bin/bash

TODAY="$(date +"%Y-%m-%d").md"

if [[ ! -e $TODAY ]]; then
  LAST=
  I=1
  while [[ $I -lt 30 ]]; do
   NAME=$(date -d "-$I days" +"%Y-%m-%d").md
   echo $NAME
   if [[ -e $NAME ]]; then
     LAST=$NAME
     break;
   fi
   I=$((I+1))
  done

  cat $LAST | grep -v "\[[Xx-]\]" > $TODAY
fi

ln -fs $TODAY ./today.md
vim ./today.md
